version: '3'
services:
  xmpp-server:
    image: ejabberd/ecs
    restart: 'unless-stopped'
    container_name: xmpp-server
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml
      - ./database:/home/ejabberd/database
    ports:
      - '5443:5443'
      - '5280:5280'
      - '5222:5222'
    environment:
      - CTL_ON_CREATE=register admin localhost passw0rd
